services:
  meta-server:
    build:
      context: .
      dockerfile: metadata_server/Dockerfile
    restart: always
    environment:
      - META_PORT=8001
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "${META_PORT:-8001}:8001"
    volumes:
      - ./data:/usr/src/app/data 

  node1:
    build:
      context: .
      dockerfile: storage_node/Dockerfile
    restart: always
    environment:
      - META_HOST=meta-server
      - META_PORT=8001
      - MY_IP=${MY_IP}
      - MIN_FREE_SPACE_GB=${MIN_FREE_SPACE_GB:-5}
      - NODE_PORT_1=${NODE_PORT_1:-9001}
      - NODE_STORAGE_1=data/storage
    ports:
      - "${NODE_PORT_1:-9001}:${NODE_PORT_1:-9001}"
    command: ["./node_app", "${NODE_PORT_1:-9001}", "data/storage"]
    depends_on:
      - meta-server
    volumes:
      - ${NODE_STORAGE_1:-./data/node1}:/usr/src/app/data/storage
    extra_hosts:
      - "host.docker.internal:host-gateway"